src/java/co/edu/monitoreo/controlador/CetrodatosController.java
package co.edu.monitoreo.controlador;

import co.edu.monitoreo.entidades.Cetrodatos;
import co.edu.monitoreo.controlador.util.JsfUtil;
import co.edu.monitoreo.controlador.util.JsfUtil.PersistAction;

import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;

@Named("cetrodatosController")
@SessionScoped
public class CetrodatosController implements Serializable {

    @EJB
    private co.edu.monitoreo.controlador.CetrodatosFacade ejbFacade;
    private List<Cetrodatos> items = null;
    private Cetrodatos selected;

    public CetrodatosController() {
    }

    public Cetrodatos getSelected() {
        return selected;
    }

    public void setSelected(Cetrodatos selected) {
        this.selected = selected;
    }

    protected void setEmbeddableKeys() {
    }

    protected void initializeEmbeddableKey() {
    }

    private CetrodatosFacade getFacade() {
        return ejbFacade;
    }

    public Cetrodatos prepareCreate() {
        selected = new Cetrodatos();
        initializeEmbeddableKey();
        return selected;
    }

    public void create() {
        persist(PersistAction.CREATE, ResourceBundle.getBundle("/Bundle").getString("CetrodatosCreated"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public void update() {
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/Bundle").getString("CetrodatosUpdated"));
    }

    public void destroy() {
        persist(PersistAction.DELETE, ResourceBundle.getBundle("/Bundle").getString("CetrodatosDeleted"));
        if (!JsfUtil.isValidationFailed()) {
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public List<Cetrodatos> getItems() {
        if (items == null) {
            items = getFacade().findAll();
        }
        return items;
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction != PersistAction.DELETE) {
                    getFacade().edit(selected);
                } else {
                    getFacade().remove(selected);
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            }
        }
    }

    public Cetrodatos getCetrodatos(java.lang.Integer id) {
        return getFacade().find(id);
    }

    public List<Cetrodatos> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<Cetrodatos> getItemsAvailableSelectOne() {
        return getFacade().findAll();
    }

    @FacesConverter(forClass = Cetrodatos.class)
    public static class CetrodatosControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            CetrodatosController controller = (CetrodatosController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "cetrodatosController");
            return controller.getCetrodatos(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Cetrodatos) {
                Cetrodatos o = (Cetrodatos) object;
                return getStringKey(o.getIdcendat());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), Cetrodatos.class.getName()});
                return null;
            }
        }

    }

}

web/cetrodatos/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="CetrodatosCreateDlg" widgetVar="CetrodatosCreateDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.CreateCetrodatosTitle}">
            <h:form id="CetrodatosCreateForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{cetrodatosController.selected != null}">
                        <p:outputLabel value="#{bundle.CreateCetrodatosLabel_idcendat}" for="idcendat" />
                        <p:inputText id="idcendat" value="#{cetrodatosController.selected.idcendat}" title="#{bundle.CreateCetrodatosTitle_idcendat}" required="true" requiredMessage="#{bundle.CreateCetrodatosRequiredMessage_idcendat}"/>
                        <p:outputLabel value="#{bundle.CreateCetrodatosLabel_fecha}" for="fecha" />
                        <p:calendar id="fecha" pattern="MM/dd/yyyy" value="#{cetrodatosController.selected.fecha}" title="#{bundle.EditCetrodatosTitle_fecha}" required="true" requiredMessage="#{bundle.EditCetrodatosRequiredMessage_fecha}" showOn="button"/>
                        <p:outputLabel value="#{bundle.CreateCetrodatosLabel_estado}" for="estado" />
                        <p:selectBooleanCheckbox id="estado" value="#{cetrodatosController.selected.estado}" required="true" requiredMessage="#{bundle.EditCetrodatosRequiredMessage_estado}"/>
                        <p:outputLabel value="#{bundle.CreateCetrodatosLabel_fkCodacti}" for="fkCodacti" />
                        <p:selectOneMenu id="fkCodacti" value="#{cetrodatosController.selected.fkCodacti}" required="true" requiredMessage="#{bundle.EditCetrodatosRequiredMessage_fkCodacti}">
                            <f:selectItems value="#{actividadController.itemsAvailableSelectOne}"
                                           var="fkCodactiItem"
                                           itemValue="#{fkCodactiItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.CreateCetrodatosLabel_fkCodprog}" for="fkCodprog" />
                        <p:selectOneMenu id="fkCodprog" value="#{cetrodatosController.selected.fkCodprog}" required="true" requiredMessage="#{bundle.EditCetrodatosRequiredMessage_fkCodprog}">
                            <f:selectItems value="#{programacionController.itemsAvailableSelectOne}"
                                           var="fkCodprogItem"
                                           itemValue="#{fkCodprogItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{cetrodatosController.create}" value="#{bundle.Save}" update="display,:CetrodatosListForm:datalist,:growl" oncomplete="handleSubmit(args,'CetrodatosCreateDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="CetrodatosCreateDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/cetrodatos/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="CetrodatosEditDlg" widgetVar="CetrodatosEditDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.EditCetrodatosTitle}">
            <h:form id="CetrodatosEditForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{cetrodatosController.selected != null}">
                        <p:outputLabel value="#{bundle.EditCetrodatosLabel_idcendat}" for="idcendat" />
                        <p:inputText id="idcendat" value="#{cetrodatosController.selected.idcendat}" title="#{bundle.EditCetrodatosTitle_idcendat}" required="true" requiredMessage="#{bundle.EditCetrodatosRequiredMessage_idcendat}"/>
                        <p:outputLabel value="#{bundle.EditCetrodatosLabel_fecha}" for="fecha" />
                        <p:calendar id="fecha" pattern="MM/dd/yyyy" value="#{cetrodatosController.selected.fecha}" title="#{bundle.EditCetrodatosTitle_fecha}" required="true" requiredMessage="#{bundle.EditCetrodatosRequiredMessage_fecha}" showOn="button"/>
                        <p:outputLabel value="#{bundle.EditCetrodatosLabel_estado}" for="estado" />
                        <p:selectBooleanCheckbox id="estado" value="#{cetrodatosController.selected.estado}" required="true" requiredMessage="#{bundle.EditCetrodatosRequiredMessage_estado}"/>
                        <p:outputLabel value="#{bundle.EditCetrodatosLabel_fkCodacti}" for="fkCodacti" />
                        <p:selectOneMenu id="fkCodacti" value="#{cetrodatosController.selected.fkCodacti}" required="true" requiredMessage="#{bundle.EditCetrodatosRequiredMessage_fkCodacti}">
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{actividadController.itemsAvailableSelectOne}"
                                           var="fkCodactiItem"
                                           itemValue="#{fkCodactiItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.EditCetrodatosLabel_fkCodprog}" for="fkCodprog" />
                        <p:selectOneMenu id="fkCodprog" value="#{cetrodatosController.selected.fkCodprog}" required="true" requiredMessage="#{bundle.EditCetrodatosRequiredMessage_fkCodprog}">
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{programacionController.itemsAvailableSelectOne}"
                                           var="fkCodprogItem"
                                           itemValue="#{fkCodprogItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{cetrodatosController.update}" value="#{bundle.Save}" update="display,:CetrodatosListForm:datalist,:growl" oncomplete="handleSubmit(args, 'CetrodatosEditDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="CetrodatosEditDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/cetrodatos/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">


        <ui:define name="title">
            <h:outputText value="#{bundle.ListCetrodatosTitle}"></h:outputText>
        </ui:define>

        <ui:define name="body">
            <h:form id="CetrodatosListForm">
                <p:panel header="#{bundle.ListCetrodatosTitle}">
                    <p:dataTable id="datalist" value="#{cetrodatosController.items}" var="item"
                                 selectionMode="single" selection="#{cetrodatosController.selected}"
                                 paginator="true"
                                 rowKey="#{item.idcendat}"
                                 rows="10"
                                 rowsPerPageTemplate="10,20,30,40,50"
                                 >

                        <p:ajax event="rowSelect"   update="createButton viewButton editButton deleteButton"/>
                        <p:ajax event="rowUnselect" update="createButton viewButton editButton deleteButton"/>

                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListCetrodatosTitle_idcendat}"/>
                            </f:facet>
                            <h:outputText value="#{item.idcendat}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListCetrodatosTitle_fecha}"/>
                            </f:facet>
                            <h:outputText value="#{item.fecha}">
                                <f:convertDateTime pattern="MM/dd/yyyy" />
                            </h:outputText>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListCetrodatosTitle_estado}"/>
                            </f:facet>
                            <p:selectBooleanCheckbox value="#{item.estado}" disabled="true"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListCetrodatosTitle_fkCodacti}"/>
                            </f:facet>
                            <h:outputText value="#{item.fkCodacti}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListCetrodatosTitle_fkCodprog}"/>
                            </f:facet>
                            <h:outputText value="#{item.fkCodprog}"/>
                        </p:column>
                        <f:facet name="footer">
                            <p:commandButton id="createButton" icon="ui-icon-plus"   value="#{bundle.Create}" actionListener="#{cetrodatosController.prepareCreate}" update=":CetrodatosCreateForm" oncomplete="PF('CetrodatosCreateDialog').show()"/>
                            <p:commandButton id="viewButton"   icon="ui-icon-search" value="#{bundle.View}" update=":CetrodatosViewForm" oncomplete="PF('CetrodatosViewDialog').show()" disabled="#{empty cetrodatosController.selected}"/>
                            <p:commandButton id="editButton"   icon="ui-icon-pencil" value="#{bundle.Edit}" update=":CetrodatosEditForm" oncomplete="PF('CetrodatosEditDialog').show()" disabled="#{empty cetrodatosController.selected}"/>
                            <p:commandButton id="deleteButton" icon="ui-icon-trash"  value="#{bundle.Delete}" actionListener="#{cetrodatosController.destroy}" update=":growl,datalist" disabled="#{empty cetrodatosController.selected}"/>
                        </f:facet>
                    </p:dataTable>
                </p:panel>
            </h:form>

            <ui:include src="Create.xhtml"/>
            <ui:include src="Edit.xhtml"/>
            <ui:include src="View.xhtml"/>
        </ui:define>
    </ui:composition>

</html>

web/cetrodatos/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="CetrodatosViewDlg" widgetVar="CetrodatosViewDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.ViewCetrodatosTitle}">
            <h:form id="CetrodatosViewForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{cetrodatosController.selected != null}">
                        <h:outputText value="#{bundle.ViewCetrodatosLabel_idcendat}"/>
                        <h:outputText value="#{cetrodatosController.selected.idcendat}" title="#{bundle.ViewCetrodatosTitle_idcendat}"/>
                        <h:outputText value="#{bundle.ViewCetrodatosLabel_fecha}"/>
                        <h:outputText value="#{cetrodatosController.selected.fecha}" title="#{bundle.ViewCetrodatosTitle_fecha}">
                            <f:convertDateTime pattern="MM/dd/yyyy" />
                        </h:outputText>
                        <h:outputText value="#{bundle.ViewCetrodatosLabel_estado}"/>
                        <p:selectBooleanCheckbox value="#{cetrodatosController.selected.estado}" disabled="true"/>
                        <h:outputText value="#{bundle.ViewCetrodatosLabel_fkCodacti}"/>
                        <h:outputText value="#{cetrodatosController.selected.fkCodacti}" title="#{bundle.ViewCetrodatosTitle_fkCodacti}"/>
                        <h:outputText value="#{bundle.ViewCetrodatosLabel_fkCodprog}"/>
                        <h:outputText value="#{cetrodatosController.selected.fkCodprog}" title="#{bundle.ViewCetrodatosTitle_fkCodprog}"/>
                    </p:panelGrid>
                    <p:commandButton value="#{bundle.Close}" onclick="CetrodatosViewDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>